"""initial schema

Revision ID: f5d16b0094db
Revises: 
Create Date: 2026-03-20 04:35:22.719372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d16b0094db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=512), nullable=False),
    sa.Column('structure', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_points_level'), 'grammar_points', ['level'], unique=False)
    op.create_index(op.f('ix_grammar_points_slug'), 'grammar_points', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vocab_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('translation', sa.String(length=255), nullable=False),
    sa.Column('part_of_speech', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('example_sentence', sa.String(length=1024), nullable=True),
    sa.Column('example_translation', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('tags', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocab_items_level'), 'vocab_items', ['level'], unique=False)
    op.create_index(op.f('ix_vocab_items_word'), 'vocab_items', ['word'], unique=False)
    op.create_table('grammar_examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grammar_point_id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.String(length=1024), nullable=False),
    sa.Column('translation', sa.String(length=1024), nullable=False),
    sa.Column('highlight', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grammar_point_id'], ['grammar_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_examples_grammar_point_id'), 'grammar_examples', ['grammar_point_id'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grammar_point_id', sa.Integer(), nullable=True),
    sa.Column('vocab_item_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('sentence', sa.String(length=1024), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grammar_point_id'], ['grammar_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocab_item_id'], ['vocab_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_grammar_point_id'), 'prompts', ['grammar_point_id'], unique=False)
    op.create_index(op.f('ix_prompts_vocab_item_id'), 'prompts', ['vocab_item_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('prompt_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_answers_prompt_id'), 'prompt_answers', ['prompt_id'], unique=False)
    op.create_table('review_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=True),
    sa.Column('user_answer', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('missing_accent', sa.Boolean(), nullable=False),
    sa.Column('spacing_normalized', sa.Boolean(), nullable=False),
    sa.Column('expected_answer', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_log_local_date'), 'review_log', ['local_date'], unique=False)
    op.create_index(op.f('ix_review_log_prompt_id'), 'review_log', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_review_log_user_id'), 'review_log', ['user_id'], unique=False)
    op.create_table('review_state',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'prompt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_state')
    op.drop_index(op.f('ix_review_log_user_id'), table_name='review_log')
    op.drop_index(op.f('ix_review_log_prompt_id'), table_name='review_log')
    op.drop_index(op.f('ix_review_log_local_date'), table_name='review_log')
    op.drop_table('review_log')
    op.drop_index(op.f('ix_prompt_answers_prompt_id'), table_name='prompt_answers')
    op.drop_table('prompt_answers')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_prompts_vocab_item_id'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_grammar_point_id'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_grammar_examples_grammar_point_id'), table_name='grammar_examples')
    op.drop_table('grammar_examples')
    op.drop_index(op.f('ix_vocab_items_word'), table_name='vocab_items')
    op.drop_index(op.f('ix_vocab_items_level'), table_name='vocab_items')
    op.drop_table('vocab_items')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_grammar_points_slug'), table_name='grammar_points')
    op.drop_index(op.f('ix_grammar_points_level'), table_name='grammar_points')
    op.drop_table('grammar_points')
    # ### end Alembic commands ###
